[package]
name = "spot"
version = "0.1.0"
edition = "2018"

[dependencies.gtk]
version = "0.8.1"
features = ["v3_24"]

[dependencies.gdk]
version = "0.12.1"
features = ["v3_24"]

[dependencies.gio]
version = "0.8.1"
features = ["v2_60"]

[dependencies.glib]
version = "0.9.2"
features = ["v2_60"]

[dependencies.librespot]
version = "0.1.1"
features = ["pulseaudio-backend"]

[dependencies.protobuf]
version = "2.8.1"

[dependencies.tokio-core]
version = "0.1.17"

[dependencies.futures01]
version = "0.1.29"

[dependencies.futures]
package = "futures"
version = "0.3.5"
features = ["compat"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
isahc = { version = "0.9", features = ["json"] }
secret-service = "1.1.0"
gdk-pixbuf = "0.8.0"
