name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://fedora:33
      run: |
        dnf -y install gcc ccache make meson \
          desktop-file-utils gtk3-devel \
          rust rustfmt cargo \
          alsa-lib-devel openssl-devel pulseaudio-libs-devel
        meson target
        cargo fmt -- --check && meson install -C target
        meson test -C target
